# Generated by Django 5.0.1 on 2024-01-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookTitle', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Author', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('Volume', models.CharField(blank=True, max_length=255, null=True)),
                ('Language', models.CharField(max_length=255)),
                ('OldShelfCode', models.CharField(max_length=255)),
                ('OldAccNo', models.CharField(max_length=255)),
                ('Publisher', models.CharField(max_length=255)),
                ('YearOfPublication', models.CharField(max_length=255)),
                ('NewShelfCode', models.CharField(blank=True, max_length=255, null=True)),
                ('Checked', models.CharField(blank=True, max_length=255, null=True)),
                ('ISBN', models.CharField(max_length=255)),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], default='Available', max_length=255)),
            ],
        ),
    ]
