# Generated by Django 5.0.3 on 2024-03-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlib', '0002_alter_book_yearofpublication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='BookId',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
