# Generated by Django 4.2.11 on 2024-04-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlib', '0003_remove_book_id_book_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
